theme: jekyll-theme-cayman
title: TheEBBGaming
description: A programmer-geek-gamer kid from the middle of nowhere.
url: "https://theebbgaming.github.io/home/"
twitter_username: ebb_the
github_username: TheEBBGaming
